dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  kovan:
    verify: True
  goerli:
    verify: True
  mainnet-fork-dev:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
compiler:
  solc:
    version: '0.8.17'
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0